#[11:0]数码管
set_property PACKAGE_PIN W4 [get_ports {DISP[11]}]
set_property PACKAGE_PIN V4 [get_ports {DISP[10]}]
set_property PACKAGE_PIN U4 [get_ports {DISP[9]}]
set_property PACKAGE_PIN U2 [get_ports {DISP[8]}]
set_property PACKAGE_PIN W7 [get_ports {DISP[7]}]
set_property PACKAGE_PIN W6 [get_ports {DISP[6]}]
set_property PACKAGE_PIN U8 [get_ports {DISP[5]}]
set_property PACKAGE_PIN V8 [get_ports {DISP[4]}]
set_property PACKAGE_PIN U5 [get_ports {DISP[3]}]
set_property PACKAGE_PIN V5 [get_ports {DISP[2]}]
set_property PACKAGE_PIN U7 [get_ports {DISP[1]}]
set_property PACKAGE_PIN V7 [get_ports {DISP[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[0]}]

#时钟
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
