#时钟
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]

#[15:0]开关
set_property PACKAGE_PIN V17 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property PACKAGE_PIN V16 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property PACKAGE_PIN W16 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property PACKAGE_PIN W17 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property PACKAGE_PIN W15 [get_ports {SW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[4]}]
set_property PACKAGE_PIN V15 [get_ports {SW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[5]}]
set_property PACKAGE_PIN W14 [get_ports {SW[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[6]}]
set_property PACKAGE_PIN W13 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[7]}]
set_property PACKAGE_PIN V2 [get_ports {SW[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[8]}]
set_property PACKAGE_PIN T3 [get_ports {SW[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[9]}]
set_property PACKAGE_PIN T2 [get_ports {SW[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[10]}]
set_property PACKAGE_PIN R3 [get_ports {SW[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[11]}]
set_property PACKAGE_PIN W2 [get_ports {SW[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[12]}]


#[11:0]数码管
set_property PACKAGE_PIN W4 [get_ports {DISP[11]}]
set_property PACKAGE_PIN V4 [get_ports {DISP[10]}]
set_property PACKAGE_PIN U4 [get_ports {DISP[9]}]
set_property PACKAGE_PIN U2 [get_ports {DISP[8]}]
set_property PACKAGE_PIN W7 [get_ports {DISP[7]}]
set_property PACKAGE_PIN W6 [get_ports {DISP[6]}]
set_property PACKAGE_PIN U8 [get_ports {DISP[5]}]
set_property PACKAGE_PIN V8 [get_ports {DISP[4]}]
set_property PACKAGE_PIN U5 [get_ports {DISP[3]}]
set_property PACKAGE_PIN V5 [get_ports {DISP[2]}]
set_property PACKAGE_PIN U7 [get_ports {DISP[1]}]
set_property PACKAGE_PIN V7 [get_ports {DISP[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[0]}]