#common
#时钟
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]

#开关
set_property PACKAGE_PIN V17 [get_ports add_sub_signal]
set_property IOSTANDARD LVCMOS33 [get_ports add_sub_signal]
set_property PACKAGE_PIN V2 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property PACKAGE_PIN T3 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property PACKAGE_PIN T2 [get_ports {b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
set_property PACKAGE_PIN R3 [get_ports {b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
set_property PACKAGE_PIN W2 [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
set_property PACKAGE_PIN U1 [get_ports {a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
set_property PACKAGE_PIN T1 [get_ports {a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
set_property PACKAGE_PIN R2 [get_ports {a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[3]}]

#[11:0]数码管
set_property PACKAGE_PIN W4 [get_ports {DISP[11]}]
set_property PACKAGE_PIN V4 [get_ports {DISP[10]}]
set_property PACKAGE_PIN U4 [get_ports {DISP[9]}]
set_property PACKAGE_PIN U2 [get_ports {DISP[8]}]
set_property PACKAGE_PIN W7 [get_ports {DISP[7]}]
set_property PACKAGE_PIN W6 [get_ports {DISP[6]}]
set_property PACKAGE_PIN U8 [get_ports {DISP[5]}]
set_property PACKAGE_PIN V8 [get_ports {DISP[4]}]
set_property PACKAGE_PIN U5 [get_ports {DISP[3]}]
set_property PACKAGE_PIN V5 [get_ports {DISP[2]}]
set_property PACKAGE_PIN U7 [get_ports {DISP[1]}]
set_property PACKAGE_PIN V7 [get_ports {DISP[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DISP[0]}]

#top exclusive
set_property PACKAGE_PIN V16 [get_ports {operand_control[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operand_control[0]}]
set_property PACKAGE_PIN W16 [get_ports {operand_control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {operand_control[1]}]

#top_v2 exclusive
set_property PACKAGE_PIN U16 [get_ports LED_c]
set_property IOSTANDARD LVCMOS33 [get_ports LED_c]
set_property PACKAGE_PIN E19 [get_ports LED_o]
set_property IOSTANDARD LVCMOS33 [get_ports LED_o]